/**
 * European country name to ISO 3166-1 alpha-2 code mapping.
 * Includes English, German (Deutsch), and Danish (Dansk) names.
 *
 * Note: Denmark/Danmark/Dänemark is intentionally excluded — the caller handles that case.
 */

(function () {
  const countryCodeMap = {
    "albania": "AL",
    "albanien": "AL",
    "andorra": "AD",
    "austria": "AT",
    "österreich": "AT",
    "østrig": "AT",
    "belarus": "BY",
    "weißrussland": "BY",
    "hviderusland": "BY",
    "belgium": "BE",
    "belgien": "BE",
    "belgië": "BE",
    "bosnia and herzegovina": "BA",
    "bosnien und herzegowina": "BA",
    "bosnien-hercegovina": "BA",
    "bosnia": "BA",
    "bulgaria": "BG",
    "bulgarien": "BG",
    "croatia": "HR",
    "kroatien": "HR",
    "cyprus": "CY",
    "zypern": "CY",
    "cypern": "CY",
    "czech republic": "CZ",
    "czechia": "CZ",
    "tschechien": "CZ",
    "tjekkiet": "CZ",
    "estonia": "EE",
    "estland": "EE",
    "finland": "FI",
    "finnland": "FI",
    "france": "FR",
    "frankreich": "FR",
    "frankrig": "FR",
    "germany": "DE",
    "deutschland": "DE",
    "tyskland": "DE",
    "greece": "GR",
    "griechenland": "GR",
    "grækenland": "GR",
    "hungary": "HU",
    "ungarn": "HU",
    "iceland": "IS",
    "island": "IS",
    "ireland": "IE",
    "irland": "IE",
    "italy": "IT",
    "italien": "IT",
    "kosovo": "XK",
    "latvia": "LV",
    "lettland": "LV",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "litauen": "LT",
    "luxembourg": "LU",
    "luxemburg": "LU",
    "malta": "MT",
    "moldova": "MD",
    "moldau": "MD",
    "moldavien": "MD",
    "monaco": "MC",
    "montenegro": "ME",
    "netherlands": "NL",
    "the netherlands": "NL",
    "niederlande": "NL",
    "holland": "NL",
    "nederland": "NL",
    "nederlandene": "NL",
    "north macedonia": "MK",
    "nordmazedonien": "MK",
    "nordmakedonien": "MK",
    "macedonia": "MK",
    "norway": "NO",
    "norwegen": "NO",
    "norge": "NO",
    "poland": "PL",
    "polen": "PL",
    "portugal": "PT",
    "romania": "RO",
    "rumänien": "RO",
    "rumænien": "RO",
    "russia": "RU",
    "russland": "RU",
    "san marino": "SM",
    "serbia": "RS",
    "serbien": "RS",
    "slovakia": "SK",
    "slowakei": "SK",
    "slovakiet": "SK",
    "slovenia": "SI",
    "slowenien": "SI",
    "slovenien": "SI",
    "spain": "ES",
    "spanien": "ES",
    "españa": "ES",
    "sweden": "SE",
    "schweden": "SE",
    "sverige": "SE",
    "switzerland": "CH",
    "schweiz": "CH",
    "svejts": "CH",
    "turkey": "TR",
    "türkiye": "TR",
    "türkei": "TR",
    "tyrkiet": "TR",
    "ukraine": "UA",
    "ukraina": "UA",
    "united kingdom": "GB",
    "uk": "GB",
    "great britain": "GB",
    "britain": "GB",
    "england": "GB",
    "scotland": "GB",
    "wales": "GB",
    "großbritannien": "GB",
    "storbritannien": "GB",
    "vatican city": "VA",
    "vatican": "VA",
  };

  /**
   * Given a full location string, returns the ISO 2-letter country code or empty string.
   * Denmark is intentionally excluded — the caller handles that case.
   */
  function countryCode(locationString) {
    if (!locationString || typeof locationString !== "string") return "";
    const lower = locationString.toLowerCase();
    for (const name in countryCodeMap) {
      if (lower.includes(name)) return countryCodeMap[name];
    }
    return "";
  }

  window.countryCode = countryCode;
})();
